[project]
name = "supernova"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.6,<2.3.0",
]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"
