[package]
name = "supernova-decode"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
supernova-macros = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[[bin]]
name = "supernova-decode"
path = "main.rs"

[lib]
path = "lib.rs"
